server:
  port: 8518
  servlet:
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
        
management:
 endpoints:
  web:
   exposure:
    include: metrics,httptrace
    
spring:
  servlet:
     multipart: 
        max-file-size: 10MB
        max-request-size: 10MB
  # 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  # 设置静态文件路径
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
      web-stat-filter:
        enabled: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/seaguard?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: root
          password:
          driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true

# Mybatis Plus 设置
mybatis-plus:
  mapper-locations: classpath*:club/seaguard/app/backend/modules/**/xml/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: UUID
      table-underline: true

# Guard专用配置
guard:
  path:
    # 文件上传根目录
    upload: /opt/app/upload
    # WebApp文件路径
    webapp: /opt/app/webapp